services:
    monitor.check.runner:
        class: Liip\MonitorBundle\Check\Runner
        arguments:
            - @monitor.check_chain

    monitor.check_chain:
        class: Liip\MonitorBundle\Check\CheckChain

    monitor.health.controller:
        class: Liip\MonitorBundle\Controller\HealthCheckController
        arguments:
            - @templating
            - @monitor.check_chain
            - @monitor.check.runner
            - @monitor.helper.path

    monitor.helper.path:
        class: Liip\MonitorBundle\Helper\PathHelper
        arguments:
            - @service_container