health_interface:
    pattern: /health
    defaults:  { _controller:  monitor.health.controller:indexAction, _method: GET }

list_checks:
    pattern: /health/checks
    defaults:  { _controller:  monitor.health.controller:listAction }

run_all_checks:
    pattern:   /health/run
    defaults:  { _controller:  monitor.health.controller:runAllChecksAction }

run_single_check:
    pattern:   /health/run/{check_id}
    defaults:  { _controller:  monitor.health.controller:runSingleCheckAction }